### ISSUE TITLE
Adapter.js ?

### ISSUE THREAD

**Issue by sualko** [otalk/traceablepeerconnection#11]
Hey guys,

sorry to disturb you once again. I get a couple of deprecated warnings in FF and while looking at the code, I was wondering, why webrtc-adapter is [included in this project](https://github.com/otalk/traceablepeerconnection/blob/master/index.js#L4), but never used. Would it not be easier to use the browser shim of webrtc-adapter?

**Comment by tgabi333** [comment]
adapter.js wraps the browser implementation to meet the specs. This is the default usage of adapter.js, just to include it and it overrides the global objects. No need to use the imported library.

**Comment by sualko** [comment]
Thanks for that information. I saw only the module.export in the core-adapter file.
