### ISSUE TITLE
prototype methods should return

### ISSUE THREAD

**Issue by xdumaine** [otalk/traceablepeerconnection#8]
We should return in the calls to these underlying methods so that consumers can promise chain them.

i.e., simply adding a return onto this - https://github.com/otalk/traceablepeerconnection/blob/master/index.js#L195

Any objections before I do this @fippo @legastero @tgabi333?

**Comment by xdumaine** [comment]
Motivation for this: when hitting [this](https://github.com/otalk/RTCPeerConnection/issues/67) problem, the error event is being emitted, but I'm getting this in the console, because the promise has no `catch`

`adapter-1.0.4.js:281 Uncaught (in promise) DOMException: Error processing ICE candidate`

**Comment by fippo** [comment]
fixed in #10
